sudo: required

language: go

go:
  - 1.7.x
install:
  - echo "Please don't go get"
  
services:
  - docker

before_script:
- curl -sSL test.docker.com | sudo -E sh

script:
  - go get -d -v
  - go build
  - ./build_samples.sh
#  - ./deploy_samples.sh # requires a deployed FaaS
