provider:
  name: faas
  gateway: http://192.168.1.224:8080  # can be a remote server
  network: "func_functions"       # this is optional and defaults to func_functions

functions:
  kfr2-datetime:
    lang: Dockerfile
    handler: ./functions/datetime
    image: kfr2/rpi-faas-datetime
